-- 授予权限给 role_sys
GRANT USAGE ON SCHEMA agent TO role_sys;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA agent TO role_sys;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA agent TO role_sys;

-- 自动为未来创建的表分配权限
ALTER DEFAULT PRIVILEGES IN SCHEMA agent GRANT ALL ON TABLES TO role_sys;
